remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Bearleargais
description: Translation of Nualeargais.

# Define navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "Chapter 1"
    url: "/chapter1/"
  - title: "Chapter 2"
    url: "/chapter2/"
  # Add more chapters as needed

# Optional: Define collections for chapters (advanced)
collections:
  chapters:
    output: true
    permalink: /:path/
